### ISSUE TITLE
Issue With Speaker Labeling

### ISSUE THREAD

**Issue by Uzzije** [Picovoice/falcon#20]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Falcon docs
- [X] I have searched the existing issues for Falcon

### SDK

Python

### Falcon package version

1.0

### Framework version

Python3.8

### Platform

macOS (x86_64, arm64)

### OS/Browser version

macOS 14.5

### Describe the bug

The speaker labeling isn't quite accurrate. Is there a way to set the fix number of speakers?

### Steps To Reproduce

import pvfalcon

falcon = pvfalcon.create(access_key='${ACCESS_KEY}')

print(falcon.process_file('${AUDIO_PATH}'))

### Expected Behavior

The file I used should have only had three speakers, instead it detected 9.

**Comment by mrrostam** [comment]
Unfortunately, there's no way to adjust the number of speakers in the current version of Falcon. However, Falcon is typically quite accurate at estimating the correct number unless there's an issue with the audio quality. If you'd like, you can send a sample to `hello@picovoice.ai`, and we can investigate the cause of this behavior.
