### ISSUE TITLE
Picovoice Documentation Issue (/docs/quick-start/falcon-python/)

### ISSUE THREAD

**Issue by linhld0811** [Picovoice/falcon#30]
I followed up this documents to try demo speaker diarization model's picovoice but i got 2 problems:
1. The model took a long time for initialization (~20 minutes)
2. An error when init model: 
FalconActivationError: Initialization failed:
  [0] Picovoice Error (code `00000136`)
  [1] Picovoice Error (code `00000136`)
  [2] Picovoice Error (code `0000012C`)
  [3] Picovoice Error (code `00000136`)
Please give me some suggestion to can try this. Thanks!

**Comment by ksyeo1010** [comment]
What command did you use? device? do you have internet connection?
Provide any other detailed information
